apiVersion: v1
kind: Service
metadata:
  name: dotnetdemo
  namespace: puma
spec:
  selector:
    app: dotnetdemo
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000